In [2]:
import numpy as np

# Soru 1

In [4]:
muz = np.arange(30).reshape(15,2)
print(muz)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]
 [24 25]
 [26 27]
 [28 29]]


# Soru 2

In [10]:
elma = np.random.randint(0,100,60).reshape(3,4,5)
print(elma)

[[[57 50 92 63 93]
  [99 73 38 33 18]
  [36 61 98 34 20]
  [85 13 83 62 38]]

 [[40 28 50 85 65]
  [57 87 78 18 74]
  [96 15 59 86 71]
  [98  3 24  3  4]]

 [[31 45 51 64 34]
  [98 41 49 34 28]
  [32 63 62 52 95]
  [50 56 87 69 25]]]


In [11]:
elma.shape

(3, 4, 5)

In [12]:
elma.ndim

3

# Soru 3

In [17]:
kivi = np.random.randint(0,10, size = (4,5))
print(kivi)

[[0 2 3 9 6]
 [4 1 0 9 4]
 [6 4 6 7 8]
 [3 8 3 7 8]]


In [18]:
kivi.reshape(-1)

array([0, 2, 3, 9, 6, 4, 1, 0, 9, 4, 6, 4, 6, 7, 8, 3, 8, 3, 7, 8])

In [19]:
kivi.shape

(4, 5)

In [20]:
kivi.ndim

2

# Soru 4

In [21]:
karma = np.random.randint(0,20,size = (4,5))
print(karma)

[[19  7 10 11  1]
 [ 7  0  6 14 17]
 [11 18  7 15  7]
 [ 3  0 12  2  2]]


In [22]:
# for

for x in karma:
  for y in x:
    print(y)

19
7
10
11
1
7
0
6
14
17
11
18
7
15
7
3
0
12
2
2


In [24]:
#nditer
for x in np.nditer(karma):
  print(x)

19
7
10
11
1
7
0
6
14
17
11
18
7
15
7
3
0
12
2
2


# Soru 5

In [27]:
ilk = np.array([5,10,15,20,25,30])
son = np.array([1,2,3,4,5,6])

In [28]:
ilk + son

array([ 6, 12, 18, 24, 30, 36])

In [29]:
ilk - son

array([ 4,  8, 12, 16, 20, 24])

In [30]:
ilk * son

array([  5,  20,  45,  80, 125, 180])

In [31]:
ilk / son

array([5., 5., 5., 5., 5., 5.])

# Soru 6

In [32]:
kavun = np.random.randint(0,100,10)
print(kavun)

[33 16 56 30 92 40 29 57 21 90]


In [33]:
kavun.sum()

464

In [34]:
kavun.mean()

46.4

In [35]:
kavun.max()

92

In [36]:
kavun.min()

16

In [37]:
kavun.var()

654.6400000000001

In [38]:
kavun.std()

25.585933635495895

# Soru 7

In [42]:
arr1 = np.arange(0,20)
print(arr1)
arr2 = np.arange(500,531)
print(arr2)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[500 501 502 503 504 505 506 507 508 509 510 511 512 513 514 515 516 517
 518 519 520 521 522 523 524 525 526 527 528 529 530]


In [43]:
np.concatenate([arr1,arr2], axis = 0)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19, 500, 501, 502, 503, 504, 505,
       506, 507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518,
       519, 520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530])

# Soru 8

In [45]:
üzüm = np.arange(15,51)
print(üzüm)
muz = np.arange(10,101)
print(muz)

[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50]
[ 10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27
  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45
  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63
  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81
  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99
 100]


In [47]:
ba = np.concatenate([üzüm,muz], axis = 0)

In [51]:
ba[25:51] = 888
print(ba)

[ 15  16  17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32
  33  34  35  36  37  38  39 888 888 888 888 888 888 888 888 888 888 888
 888 888 888 888 888 888 888 888 888 888 888 888 888 888 888  25  26  27
  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45
  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63
  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81
  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99
 100]


# Soru 9

In [57]:
array1 = np.arange(0,40).reshape(8,5)
print(array1)
array2 = np.arange(320,360).reshape(8,5)
print(array2)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]]
[[320 321 322 323 324]
 [325 326 327 328 329]
 [330 331 332 333 334]
 [335 336 337 338 339]
 [340 341 342 343 344]
 [345 346 347 348 349]
 [350 351 352 353 354]
 [355 356 357 358 359]]


In [58]:
np.concatenate([array1,array2],axis = 0)

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34],
       [ 35,  36,  37,  38,  39],
       [320, 321, 322, 323, 324],
       [325, 326, 327, 328, 329],
       [330, 331, 332, 333, 334],
       [335, 336, 337, 338, 339],
       [340, 341, 342, 343, 344],
       [345, 346, 347, 348, 349],
       [350, 351, 352, 353, 354],
       [355, 356, 357, 358, 359]])

In [59]:
np.concatenate([array1,array2],axis = 1)

array([[  0,   1,   2,   3,   4, 320, 321, 322, 323, 324],
       [  5,   6,   7,   8,   9, 325, 326, 327, 328, 329],
       [ 10,  11,  12,  13,  14, 330, 331, 332, 333, 334],
       [ 15,  16,  17,  18,  19, 335, 336, 337, 338, 339],
       [ 20,  21,  22,  23,  24, 340, 341, 342, 343, 344],
       [ 25,  26,  27,  28,  29, 345, 346, 347, 348, 349],
       [ 30,  31,  32,  33,  34, 350, 351, 352, 353, 354],
       [ 35,  36,  37,  38,  39, 355, 356, 357, 358, 359]])

# Soru 10

In [ ]:
# 9. sorudaki arrayleri axis = 2'de concatenate etmek için 3 boyutlu hale getirmeliyiz.

In [77]:
array3d1=array1.reshape((2,4,5))

In [78]:
array3d2= array2.reshape((2,4,5))

In [80]:
np.concatenate([array3d1,array3d2], axis = 2)

array([[[  0,   1,   2,   3,   4, 320, 321, 322, 323, 324],
        [  5,   6,   7,   8,   9, 325, 326, 327, 328, 329],
        [ 10,  11,  12,  13,  14, 330, 331, 332, 333, 334],
        [ 15,  16,  17,  18,  19, 335, 336, 337, 338, 339]],

       [[ 20,  21,  22,  23,  24, 340, 341, 342, 343, 344],
        [ 25,  26,  27,  28,  29, 345, 346, 347, 348, 349],
        [ 30,  31,  32,  33,  34, 350, 351, 352, 353, 354],
        [ 35,  36,  37,  38,  39, 355, 356, 357, 358, 359]]])

# Soru 11

In [85]:
array11= np.array([1,20,25,4,4,5,4,4,1,6,9,12,1,5])
print(array11)

[ 1 20 25  4  4  5  4  4  1  6  9 12  1  5]


In [86]:
np.where(array11 == 5)

(array([ 5, 13]),)

# Soru 12

In [87]:
np.where(array11%2 == 0 )

(array([ 1,  3,  4,  6,  7,  9, 11]),)

# Soru 13

In [88]:
np.where(array11 > 4)

(array([ 1,  2,  5,  9, 10, 11, 13]),)

# Soru 14

In [89]:
np.where(array11%5 == 0)

(array([ 1,  2,  5, 13]),)

# Soru 15

In [100]:
np.random.randint(85,101)

96

# Soru 16

In [93]:
ikiler = np.random.randint(10,100, size = (3,3))
print(ikiler)

[[97 39 87]
 [12 38 48]
 [44 52 25]]


# Soru 17

In [95]:
of = np.random.randint(35,60,10)
print(of)

[52 44 45 41 56 53 44 53 57 55]


In [96]:
np.random.choice(of)

52

# Soru 18

In [99]:
sadece = np.array([3,8,10,53,3,8,10,53,3,8]).reshape(2,5)
print(sadece)

[[ 3  8 10 53  3]
 [ 8 10 53  3  8]]
