# Soru 1

In [ ]:
import numpy as np

In [ ]:
array3d = np.array([[[1,2,3], [4,5,6]]])
array3d

array([[[1, 2, 3],
        [4, 5, 6]]])

In [ ]:
print(array3d.ndim)

3


# Soru 2

In [ ]:
np.array([])
np.arange(30,118,6)

array([ 30,  36,  42,  48,  54,  60,  66,  72,  78,  84,  90,  96, 102,
       108, 114])

# Soru 3

In [ ]:
np.array([])
array91 = np.linspace(50,500,91,dtype=int)
len(array91)


91

# Soru 4

In [ ]:
np.logspace(2,5,8)

array([   100.        ,    268.26957953,    719.685673  ,   1930.69772888,
         5179.47467923,  13894.95494373,  37275.93720315, 100000.        ])

# Soru 5

In [ ]:
array3x3 = np.arange(0,9).reshape(3,3)
print(array3x3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


# Soru 6

In [ ]:
np.zeros((6,6), dtype=int)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

# Soru 7

In [ ]:
np.ones((4,4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

# Soru 8

In [ ]:
np.eye(8,dtype=int)

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1]])

#Soru 9

In [ ]:
matris = np.zeros((5, 5), dtype=int)
np.fill_diagonal(matris, 3)

print(matris)

[[3 0 0 0 0]
 [0 3 0 0 0]
 [0 0 3 0 0]
 [0 0 0 3 0]
 [0 0 0 0 3]]


#Soru 10

In [ ]:
np.random.rand(6)

array([0.38702641, 0.67087559, 0.06876907, 0.2075923 , 0.16735887,
       0.6094084 ])

#Soru 11

In [ ]:
armut = np.random.randint(50,101,(5,2))
print(armut)

[[92 73]
 [61 86]
 [95 96]
 [51 54]
 [84 50]]


In [ ]:
armut.shape

(5, 2)

# Soru 12

In [ ]:
elma = np.random.randint(100,1000,(2,5,5))
print(elma)


[[[924 206 126 158 748]
  [476 608 501 740 665]
  [198 795 452 158 546]
  [376 139 366 492 380]
  [454 607 133 783 881]]

 [[495 834 502 628 459]
  [425 793 764 694 667]
  [722 814 567 721 778]
  [958 901 806 642 551]
  [765 892 507 301 551]]]


In [ ]:
elma.shape


(2, 5, 5)

In [ ]:
elma.ndim

3

# Soru 13

In [ ]:
karpuz = np.random.randint(0,101,10)
print(karpuz)

[56 89 58 11 57 14 31 77 19 49]


In [ ]:
max(karpuz)

89

In [ ]:
min(karpuz)

11

In [ ]:
karpuz.argmax()

1

In [ ]:
karpuz.argmin()

3

# Soru 14

In [ ]:
kivi = np.random.randint(300,501,(2,2,5))
print(kivi)

[[[305 387 434 383 353]
  [496 383 400 328 447]]

 [[411 367 350 435 419]
  [335 368 348 389 447]]]


In [ ]:
kivi.argmax()

5

In [ ]:
kivi[0][1][0]

496

In [ ]:
kivi[0][0][0]

305

# Soru 15

In [ ]:
kiraz = np.linspace(0,50,50,dtype=int)
print(kiraz)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 50]


In [ ]:
kiraz[20:35] = 500
print(kiraz)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  50]
